title: SITAquant
description: A simplified resource for stable isotope tracer analysis from mass spectrometry data

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
